### ISSUE TITLE
Put flask server in a docker container

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#10]

**Comment by stuart909** [comment]
This is a decent resource.  Keep in mind that you already have a working server and you need to take into account your python requirements when you make your dockerfile.

https://blog.logrocket.com/build-deploy-flask-app-using-docker/

**Comment by stuart909** [comment]
When you create a successful docker deployment, please write done or PM me  in discord

**Comment by stuart909** [comment]
Tabriz is done

**Comment by stuart909** [comment]
Almost everyone finished

**Comment by kiserd** [comment]
Logan is done. Or, I should say that I have built an image of the pengin-pie package, ran this in docker locally, and requested/viewed the app (locally) via Chrome. I may have strayed from best practices at times.

**Comment by yeaung00** [comment]
Ye is done

**Comment by achen236** [comment]
Andy is done

**Comment by loknara** [comment]
Lokesh is done

**Comment by imamyy** [comment]
Amy is done

**Comment by DanielRiquelmeReb** [comment]
Daniel is done

**Comment by ziniwang** [comment]
Zini is done

**Comment by jegasuguna** [comment]
Suguna is done
