### ISSUE TITLE
[BUG] 72-Profile-V2 company button bugged

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#109]
**Describe the bug**
In the profile menu, the company profile button is not linked to the company page

**To Reproduce**
1. Login
2. Go to profile page
3. Click company

**Expected behavior**
Expect to see the company pages we made

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Browser firefox
 - Version irrelevant

**Comment by stuart909** [comment]
git fetch origin
git checkout 109-bug-72-profile-v2-company-button-bugged-patch

**Comment by jmm28** [comment]
I'm also having issues with viewing the profile page, as well as the post-login screen. I think these might be from me pulling the profile/company routes into their own file and missing some necessary changes.

**Comment by stuart909** [comment]
make sure you:
```
git fetch
git checkout -f 72-profile-v2
```
