### ISSUE TITLE
run the flask server with docker in your IDE terminal

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#11]

**Comment by stuart909** [comment]
After you have a good docker container for your flask server, make sure you can run it from your IDE terminal.  When you are done, just say done here or PM me on discord.

**Comment by stuart909** [comment]
Tabriz ran flask through the docker container in pycharm.

**Comment by stuart909** [comment]
Those that are not finished can pull Tabriz branch

**Comment by yeaung00** [comment]
Ye is done

**Comment by DanielRiquelmeReb** [comment]
Daniel is done

**Comment by loknara** [comment]
Lokesh is done

**Comment by ziniwang** [comment]
Zini is done

**Comment by imamyy** [comment]
Amy is done

**Comment by achen236** [comment]
Andy is done. Actually forgot to comment earlier.

**Comment by jegasuguna** [comment]
Suguna is done
