### ISSUE TITLE
Company Page Patch [FEATURE REQUEST]

### ISSUE THREAD

**Issue by jmm28** [Pengin-Open-Source/pengin-pie#116]
**Description**
Improvements to the company page, as per earlier discussion with Stuart. 

Changes can be found in the [jasmine-company-patch](https://github.com/Pengin-Open-Source/pengin-pie/tree/jasmine-company-patch) branch. 

**Examples of Changes**

I moved the Companies header and links to the left div instead of the right column. The companies page also now uses the profile links (whose code is now directly in profile_main.html):
![Screen Shot 2022-07-27 at 2 05 29 PM](https://user-images.githubusercontent.com/65846682/181352572-907279da-2cdf-4a55-a263-33f75eb73c59.png)

![Screen Shot 2022-07-27 at 2 29 54 PM](https://user-images.githubusercontent.com/65846682/181356188-f0e12e58-77b5-456d-9ff4-b7b904f722b7.png)

(I also had to make a quick update to the code since I misplaced a </div> tag, which would occasionally push the links into the left column).

**Comment by stuart909** [comment]
can you add your branch into the Development portion on the right?

**Comment by stuart909** [comment]
also, could you fill out more details according to the template?  Pictures and examples will be helpful.

**Comment by jmm28** [comment]
> also, could you fill out more details according to the template? Pictures and examples will be helpful.

Sure! Sorry about that; I wasn't too sure what to put into the template.

**Comment by stuart909** [comment]
This looks a lot better.

I will go ahead and promote this to a feature if you can share with us what tasks (issues) you think we need to create and which teams will be responsible for the implementation.

**Comment by jmm28** [comment]
> This looks a lot better.
> 
> I will go ahead and promote this to a feature if you can share with us what tasks (issues) you think we need to create and which teams will be responsible for the implementation.

Thanks! [This pull request](https://github.com/Pengin-Open-Source/pengin-pie/pull/118) already has the implemented changes, so I don't think any additional tasks are necessary.
