### ISSUE TITLE
push changes to your own branch

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#12]

**Comment by stuart909** [comment]
When you have a complete flask deployment working in your local branch, push it to your remote branch.

Write done when complete, or PM me in discord.

**Comment by stuart909** [comment]
Tabriz pushed his project to his test branch

**Comment by stuart909** [comment]
those that are not finished can pull tabriz branch

**Comment by kiserd** [comment]
Logan is done.

**Comment by achen236** [comment]
Andy is done

**Comment by loknara** [comment]
Lokesh is done

**Comment by yeaung00** [comment]
Ye is done

**Comment by DanielRiquelmeReb** [comment]
Daniel is done

**Comment by ziniwang** [comment]
Zini is done

**Comment by imamyy** [comment]
Amy is done

**Comment by jegasuguna** [comment]
Suguna is done.
