### ISSUE TITLE
[FEATURE REQUEST] Forum Form Folders and Breadcrumbs

### ISSUE THREAD

**Issue by achen236** [Pengin-Open-Source/pengin-pie#120]
**Explanation**
This is currently my forum form that I have built in branch 86-forum-form-andy-2. 

https://github.com/Pengin-Open-Source/pengin-pie/issues/86#issuecomment-1197778724
I think if folders are stored this way it is too limited. I think this way threads won't be able to reference and contain other threads and navigate between them.

**Brief**
How folders are stored and found in database.

**Outline**
A folder is just a post with content == None. This way a folder can have a `title: string`, `threadid: int` and `id: int`, so a folder can know what folder is its parent. The URL are built like forums/<int:thread> with forums/0 being the default home page. A query for posts and threads shown below. 

```
posts_folders = Forum_Post.query.filter(Forum_Post.thread == thread).order_by(Forum_Post.date.desc())
posts = posts_folders.filter(Forum_Post.thread == thread, Forum_Post.content != None).all()
threads = posts_folders.filter(Forum_Post.thread == thread, Forum_Post.content == None).all()
```
This also allows me to implement breadcrumbs between threads for better navigation. Also I added a temporary checkbox to the create post form to create a folder instead of a post. I don't know how you would add folders, I'm assuming it would be restricted by admin privilege.

This is just an option I thought of with only use of Forum_Post, but there could probably be a better implementation.

If we wanted to limit number of posts returned in query per page , pagination can also be added with route forums/<int:thread>/page/<int:page> with page 1 being the default  as forums/<int:thread>. 

For reference, I've been using https://www.plantedtank.net/forums/ for general formatting and an idea of how a forum should look like.

As previously mentioned by Stuart, the code needs to be broken down more with multiple jinja template files, which is a work in progress.

**Assign Issue**

**Priority**
- 2 

**Additional context**
<img width="1666" alt="Screen Shot 2022-07-28 at 2 52 04 PM" src="https://user-images.githubusercontent.com/57299247/181616956-afd6862c-66f6-4315-91b3-72f92a7b9b4a.png">
<img width="1665" alt="Screen Shot 2022-07-28 at 2 52 18 PM" src="https://user-images.githubusercontent.com/57299247/181616958-044afcd6-ea6b-4221-886a-d1ac5410eda2.png">
<img width="1667" alt="Screen Shot 2022-07-28 at 2 52 33 PM" src="https://user-images.githubusercontent.com/57299247/181616961-49982c41-aa64-4b98-be45-51107f7607fb.png">
<img width="1666" alt="Screen Shot 2022-07-28 at 2 52 43 PM" src="https://user-images.githubusercontent.com/57299247/181616952-52614578-b3b8-45d1-bbdf-7e14b87b6539.png">

**Comment by stuart909** [comment]
This is looking really good.  Though I would oppose the creation of so many folders.  This will get spammed and create a bunch of junk records in the database

**Comment by stuart909** [comment]
Let's try using a variant of this in the ticket forum and see how it works.
