### ISSUE TITLE
Ticket Forum Main View[ #128 ]

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#129]
**Description**
/ticket/ticket_main.html

**Details**
This is the ticket forum main view.  Support will be able to see all tickets, just like an authenticated user can see most blog posts or threads.  Threads in this case are customerID's.  CustomerID will restrict who can see the thread.  Members of customer ID, support team, or admin, will see all customer threads.

The customer will see all of their tickets, because the default view for the customer will be the main forum, which will show their customerID and all the tickets that are OPEN                             

**Parent Issue**
#128 

**Additional context**
```
git fetch origin
git checkout 129-ticket-forum-main-view-128
```

**Comment by jmm28** [comment]
Is there a support role? 
Additionally, where does the customer ID come from? Is it the current user's ID (i.e. just current_user.id)?
