### ISSUE TITLE
Ticket ORM Model

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#130]
**Description**
This is the Ticket Forum ORM model for models.py.  It is quite similar to the ForumPosts and Comment ORM, with the exception that we must account for customerID and support team restrictions.

**Ticket Table**
- id
- customerid
- summary
- content
- tags
- date
- resolutionID
- resolutionDate

**Resolution Table**
- id
- name

**Parent Issue**
#128

**Additional Context**
```
git fetch origin
git checkout 130-ticket-orm-model
```

**Comment by jmm28** [comment]
Where are ticket comments stored?
