### ISSUE TITLE
Download AWS CLI

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#14]
Please Download AWS CLI

Below is the URL documentation

**Comment by stuart909** [comment]
https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

**Comment by stuart909** [comment]
This is a prerequisite for a future task.  However, feel free to take care of this at your own leisure.  State done when complete, or PM me on discord.

**Comment by stuart909** [comment]
Kartik and Logan, please make sure you have this downloaded and let Brian know, thanks.

**Comment by kartikgrover** [comment]
Kartik is done

**Comment by achen236** [comment]
Andy is done

**Comment by yeaung00** [comment]
Ye is done

**Comment by mliaw3** [comment]
Marcus is done.

**Comment by loknara** [comment]
Lokesh is done

**Comment by DanielRiquelmeReb** [comment]
Daniel is done

**Comment by ziniwang** [comment]
Zini is done

**Comment by imamyy** [comment]
Amy is done
