### ISSUE TITLE
[FEATURE REQUEST] Refactor ORM classes and style to PEP8

### ISSUE THREAD

**Issue by jkcswd** [Pengin-Open-Source/pengin-pie#151]
There is duplication in the ORM models that can get refactored out via inheritance. Some of the code seems to not all be following the same style guidelines. I suggest using the PEP8 standard and making sure all code follows this. 

The suggested style guide and the conventions for branching should also be put in the readme so that contributors can easily see what they need to do top contribute.

**Comment by stuart909** [comment]
This is one of the goals for the Fall / Winter dev cycle.
