### ISSUE TITLE
Deploy docker to your designated Lightsail target

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#16]

**Comment by stuart909** [comment]
https://docs.aws.amazon.com/cli/latest/reference/lightsail/create-container-service-deployment.html

**Comment by stuart909** [comment]
The designated target is actually pengin opensource prod.  Let's hold off on deploying a lightsail instance

**Comment by stuart909** [comment]
Kartik and Logan, let's have a talk about this task.  The tutorials and docs I have are great, but we need to be offline about how we deploy our container.  penginopensource.org is old but it is still prod.  So we need to operate in real world and not simply shut her down with experiments.  Thanks.

**Comment by kiserd** [comment]
> Kartik and Logan, let's have a talk about this task. The tutorials and docs I have are great, but we need to be offline about how we deploy our container. penginopensource.org is old but it is still prod. So we need to operate in real world and not simply shut her down with experiments. Thanks.

Sounds great. I'll be off camping at a festival Friday - Monday. I should be good to discuss this upon return.
