### ISSUE TITLE
[FEATURE] Calendar

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#165]
**Explanation**
The showcase feature for our POS RC is the calendar.  We need a robust calendar and scheduling app integrated in the POS core stack.  There are many options publicly available, but, we will need to fork and refactor a significant portion of the code to keep our project light weight.  

This FR is for organization plans and research for the calendar app, and later tracking the development of the app.

**Brief**
- Outline features of our calendar app
- Research open source calendar options
- fork possible calendar candidates
- map out development
- build the app

**Features**

- need to have team calendars for designated roles other than "user".  This will use roles
- need to have granular calendars for users that belong to designated teams
- ORM likely has permitted teams, and the members have access to calendar app
- users should be permitted access to team or team-user calendar when assigned a token, this will likely require the USER ORM to have a access token column with a special key the is also kept somewhere with the team calendar item
- calendar needs to render daily items, best effort in the daily box.
- let's build a list form calendar, not the box one.  It can look like blog or forum posts
- this is an event based calendar
- calendar model will have an owner ID, which can be a user or company (group ID).
- need to account for time zones, so use UTC, Zulu, Greenwich.  Time rendered should us the user system time, but the time stored should always be UTC.
- pagenate with time?  select records from months, days, years, etc.

**Outline**

**Child Issues**
- [x] #221
- [x] #222
- [x] #223
- [x] #224 
- [x] #225 

**Additional context**
N/A

**Comment by jkcswd** [comment]
Basic calendar created and merged to dev.

**Comment by stuart909** [comment]
add branch 165-feature-calendar and updated it to current dev branch.
