### ISSUE TITLE
Main DIV CSS divisions

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#41]
I would like to add some CSS code for dividing up the main view window on the pengin-pie browser.  I want to get us ready to do away with the right hand information bar.  See images below:

https://cdn.discordapp.com/attachments/955221704144207882/984266585256636416/unknown.png
https://cdn.discordapp.com/attachments/955221704144207882/984266884809629716/unknown.png
https://cdn.discordapp.com/attachments/955221704144207882/984267390072262686/unknown.png
https://cdn.discordapp.com/attachments/955221704144207882/984267623053295666/unknown.png
https://cdn.discordapp.com/attachments/955221704144207882/984268129188335676/unknown.png
https://cdn.discordapp.com/attachments/955221704144207882/984268510668664852/unknown.png

**Comment by stuart909** [comment]
Jasmine,

This addition is based on our previous discussion.  I will be mostly looking for changes in the stylesheet.


git fetch origin
git checkout 41-main-div-css-divisions

**Comment by kiserd** [comment]
I'll connect with the team tomorrow re: issue specifics. The pictures are helpful, but it sounds like I am missing a little bit of context shared in a prior conversation.

**Comment by stuart909** [comment]
This is a basic CSS stylesheet request for the main window.

**Comment by stuart909** [comment]
![image](https://user-images.githubusercontent.com/58710710/176091654-11c64f66-83a5-4e33-9dac-b1def2e8027d.png)

**Comment by stuart909** [comment]
![image](https://user-images.githubusercontent.com/58710710/176092943-917fba56-575c-401a-baff-377068c4d96d.png)

**Comment by kiserd** [comment]
Awesome! Much appreciated! I saw a couple different ways of dividing out the section, so wanted to make sure we weren't going to dynamically render different sizes based on class keywords being passed from the views (or something like that).

This helps a ton!

**Comment by stuart909** [comment]
Just creating styles for the main content window

**Comment by kiserd** [comment]
I noticed that we included some styling in the `.rightcontent` div in our layout. I am FAR FROM adept in terms of front-end layouts/styling/etc, so take all of this with a grain of salt. In past projects, my teams have found success in restricting these sorts of containers to handling general layout. Then, the burden of more specific styling is placed on the templates down the inheritance chain. That approach seems to still keep layout consistent, but doesn't force us to use the exact same background color (for example). If a hunk of our website requires consistent specific styling within these containers, we could create an intermediate template that forces styling. E.g., if all of the blogpost related content needed the `rightcontent` div to have a white background, rounded borders, _px padding, etc, we could create an intermediate `blog_main.html` that handles that (but does not restrict all of the forum stuff).

![image](https://user-images.githubusercontent.com/59572911/176473594-72f644e7-7eec-4c0d-a990-0e5f4e60f076.png)

Of course, if we ALWAYS want our `leftcontent` and `rightcontent` divs to have the **exact** same styling, it would make sense to just handle all of that once and be done with it :P

@jmm28 I'll try to connect with you during your dev time this evening! I'd love to hear your thoughts!

**Comment by kiserd** [comment]
I believe `dev-07.11.2022` illustrates the teams understanding of how to resolve this issue. Andy created three intermediary templates that define the different layouts we can choose to use when displaying content.

- Home: illustrates a single container
- Products: illustrates three equal sized containers
- Blog: illustrates two containers (one being 2/3 of the viewport)

@stuart909 let us know if you want this tweaked!

**Comment by stuart909** [comment]
I'm content with what we have so far in 0.0.1b alpha2.  I am closing this issue.
