### ISSUE TITLE
[TASK] socketIO emission, receive fix

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#416]
**Details**
The template socketIO transmission needs to be modified to:
- [x] emit message to server
- [x] ask server for response

**Additional Context***
#417

**Comment by franfif** [comment]
Added function sendMessage() to send message to server from template.
Added socket io event listener "saved_message" to get new messages from server and update the div.

**Comment by franfif** [comment]
I modified the code in the pengin-pi repo, but as all development has been moved to messenger repo, I don't think I should do a pull request at this time.
