### ISSUE TITLE
[TASK] Message class event handling modification

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#417]
**Description**
The message class message_json method needs to be split into two methods

**Details**
- [x] receive_message() method must receive message and write to database only
- [x] send_message() method will be requested by a user after a user transmits.  This method will read database for updates and send the response

**Additional context**
#416

**Comment by franfif** [comment]
> send_message() method will be requested by a user after a user transmits
This method is called by the Messenger.save_message() method on the server side, to streamline the process:

**Initial design, as proposed in the original issue:**
Client: method Messenger.send_message() -> emit socketIO event "save_message"
Server: event listener for "save_message": Messenger.save_message()  -> emit event "message_saved"
Client: event listener for "message_saved" -> emit event "get_message"
Server: event listener for "get_message": Messenger.send_message()  -> emit event "saved_message"
Client: event listener for "saved_message" -> call client function create_message() to update div with message

**Design as committed**
Client: method Messenger.send_message() -> emit socketIO event "save_message"
Server: event listener for "save_message": Messenger.save_message()  -> call Messenger.send_message() method
Server: method Messenger.send_message()  -> emit event "saved_message"
Client: event listener for "saved_message" -> call client function create_message() to update div with message

This way, we avoid an unnecessary back and forth with the server and the client.

**Comment by franfif** [comment]
I modified the code in the pengin-pi repo, but as all development has been moved to messenger repo, I don't think I should do a pull request at this time.
