### ISSUE TITLE
Do away with right hand info form

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#42]
Let's find a way to get rid of the right hand information window.  I would like to reserve the use of that form for specific use cases that we will discuss later.

![image](https://user-images.githubusercontent.com/58710710/173021560-93626e1b-86ca-44ef-a0c5-bb3b5fbcdcf0.png)

**Comment by stuart909** [comment]
There is not a branch yet, we will add one when we get caught up.

**Comment by kiserd** [comment]
I am happy to trash that component, but I am a little worried about stepping on Jasmine's toes. I doubt the front-end folks are worried about little tweaks here and there, but it would be awesome to discuss at the team meeting tomorrow.

**Comment by stuart909** [comment]
sure, we can talk about it at the meeting.

**Comment by achen236** [comment]
I branched off [41-main-div-css-divisions](https://github.com/Pengin-Open-Source/pengin-pie/tree/41-main-div-css-divisions) to create a new branch:  [42-delete-right-hand-info-form](https://github.com/Pengin-Open-Source/pengin-pie/tree/42-delete-right-hand-info-form), I got rid of the info form on the home page. I also aligned the Tobu Pengin logo with the other nav items.

<img width="1667" alt="Screen Shot 2022-07-06 at 4 09 22 PM" src="https://user-images.githubusercontent.com/57299247/177634390-2973717e-1d09-4006-ae6e-38c5e306f7bf.png">
