### ISSUE TITLE
Remove dummy data from app initialization and create a more robust default website system.

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#433]
## Description:
The current project initialization in the `app/__init__.py` file includes dummy class information, referred to as "defaults." This information needs to be removed from the app initialization process. Specifically:

- **Remove Dummy Class Information:**
  - Identify and remove the dummy class information present in the `app/__init__.py` file to clean up the initialization process.

- **Update Route Code for About and Home:**
  - Modify the route code for the 'about' and 'home' pages to use correct paths in accordance with the removal of dummy data.

- **Relocate Dummy Information to app/util/defaults:**
  - Relocate the dummy information (now named "defaults") from the app initialization to `app/util/defaults`. This ensures a more organized structure and separation of concerns.

- **Update Code References to app/util/defaults:**
  - Adjust the code in the home, main layout, and about pages to reference `app/util/defaults` for default page data when the database is empty.

- **Delete App Init Dummy Class:**
  - Remove the dummy class present in the app initialization, as it is no longer needed.

This enhancement aims to streamline the initialization process, improve code organization, and create a more robust default website system. Please review and merge accordingly.

**Comment by franfif** [comment]
As far as I can see, home and about routes do not use dummy data at all.
In their respective index view, they call the first Home or About object in the database and use it. I will add access to dummy data in case the db is empty.

**Comment by franfif** [comment]
What I did in branch [433-remove-dummy-data-Franfif](https://github.com/Pengin-Open-Source/pengin-pi/tree/433-remove-dummy-data-Franfif):

- **Remove Dummy Class Information:**
  - Removed DummyHome class information present in the `app/__init__.py` file.

- **Relocate Dummy Information to app/util/defaults:**
  - Created `util/defaults/default.py` file.
  - Added default Home class and About class in `default.py`.

- **Update Route Code for About and Home:**
  - Modified the route code for the 'about' and 'home' pages to point to `util/defaults/default.py` Home and About classes when these don't exist in the database.


**[NEW]**
- **Default image:**
  - Added default image "/static/images/test.png" in `util/defaults/default.py`.
  - Modified all mentions in Pengin-Pi of "/static/images/test.png" to point to `util/defaults/default.py/image` instead 
  - Easier to maintain, if the default image is changed in the future.
