### ISSUE TITLE
[BUG] Error when trying to comment on a forum post

### ISSUE THREAD

**Issue by mvetom** [Pengin-Open-Source/pengin-pie#435]
**Describe the bug**
When you try to comment on a forum post,  an error occurs when you try to post the comment

**To Reproduce**
1. Go to Forums
2. Select Any Post in any Forum
3. Type in a comment at the bottom of the Forum post
4. Hit Post.

**Expected behavior**
The new comment should appear in the post's comment section

**Additional context**
I did not notice another bug report on this issue,  but I did see that the 360/361/362-small-bugs branch doesn't have this problem.  I don't know if a fix was placed in this branch,  or if the bug was introduced later.

**Comment by stuart909** [comment]
I fixed this when doing the other PRs..  Closing
