### ISSUE TITLE
Create project setup onboarding template

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#47]
Amy,

I think it will be better for us if we take the onboarding task cards and the tickets they possess and create a template that will guide a newcomer through all of the steps in four tickets or so.

IDE Setup ticket
Flask server ticket
NginX setup ticket
Docker setup ticket

This way, when a person onboards, they can easily be assigned a tracking ticket by a manager that can be closed when done so we know exactly who finished what.

Please consult the github ticket documentation.  I will be happy to give assistance if you need it.

**Comment by imamyy** [comment]
I will take a look at the documentation then get back to you if I have any question.

**Comment by stuart909** [comment]
Amy, Zini,

Where are we with this?

**Comment by imamyy** [comment]
I have just finished setting up a template for newcomers under issue#60. However, I could not find the NginX Setup Ticket. Please let me know if I need to fix anything, Stuart.

**Comment by stuart909** [comment]
I setup the templates.
