### ISSUE TITLE
Front end proposal

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#55]
I submit to the team a proposal that we keep using bootstrap, but change the site to have a general layout like this:

![image](https://user-images.githubusercontent.com/58710710/176784609-528c80d7-0c5f-4363-be0e-13fdb06a7692.png)

![image](https://user-images.githubusercontent.com/58710710/176784716-0c1aa356-2ff5-40c6-9817-491489c01381.png)

![image](https://user-images.githubusercontent.com/58710710/176784962-3a65c162-7b76-44f6-a85e-f7e119a1853f.png)

**Comment by kiserd** [comment]
I'm, of course, no expert wrt Jinja, but couldn't we accomplish something like this with `layout.html` structured as follows:

```
<div class="outterWrapper">
<!-- setup layout for child templates that inherit the three-div layout --!>
    <div class="firstThird">
    {% block firstThird %}{% endblock %}
    </div>
    <div class="secondThird">
    {% block secondThird %}{% endblock %}
    </div>
    <div class="thirdThird">
    {% block thirdThird %}{% endblock %}
    </div>
<!-- setup layout for child templates that inherit the two-div layout --!>
    <div class="twoThirdContainer">
    {% block twoThirdContainer %}{% endblock %}
    </div>
    <div class="oneThirdContainer">
    {% block oneThirdContainer %}{% endblock %}
    </div>
<!-- setup layout for child templates that inherit the single-div layout --!>
    <div class="singleContainer">
    {% block singleContainer %}{% endblock %}
    </div>
</div>
```

Then, when building out our child templates, depending on which layout we desire, we populate the associated blocks. Of course, if we were to mix blocks from conflicting templates, things would look very wonky.

Not married to this, just trying to keep the conversation flowing with some initial thoughts :)

**Comment by stuart909** [comment]
the layout should only have a main content view and the children should be the divisional containers, and they should have children within those containers.

**Comment by stuart909** [comment]
Layout should only be the header, styles, scripts, meta, nav, body, and footer.  Each section in layout should be a block that is dynamically loaded

**Comment by kiserd** [comment]
I gotcha. I'm still a Jinja newbie, so bear with the silly thoughts. I had assumed we wanted to restrict the styling of those containers at the highest level (`layout.html`) and let the child templates play within those boundaries.

**Comment by stuart909** [comment]
basically the layout just loads in our basic garbage.  the globals, if you will.  google meta data, scripts, css style sheets, then the basic nav bar and footer.  We also declare our main content window.  The URLs themselves will dictate what gets loaded into the main content window.  Even the nav bar can be made to be dynamically created.  The idea I propose is that we dynamically generate everything into a very mundane base layout.

**Comment by stuart909** [comment]
This is just a proposal btw.  Any other thoughts?

**Comment by kiserd** [comment]
I am all for it! I always pictured everything being dynamically created. I'm just trying to tease out how we would incorporate the DRY principle with the actual layout structure. I would guess that we don't want each individual "leaf" html template to build these containers (so we keep things super consistent and don't repeat ourselves).

Would we have intermediary templates that define the layouts that are then extended by lower level templates? E.g., `leaf.html` extends `intermediary1.html` extends `layout.html`.

Or would we have these different container layouts defined in several different templates?

**Comment by stuart909** [comment]
when a user types in a route, we specify the lowest child, or children.  Those views will extend a parent, and sometimes, those parents extend a parent.  By rendering any given child, or groups of children, they will extend their parents up the hierarchy and the page is rendered.

**Comment by kiserd** [comment]
Totes! I'm trying to determine where along the chain the containers are defined. I now know we don't want to do so in `layout.html`. However, I'm pretty sure we don't want to define those containers in each of the lowest childs. I guess I thought that the DRY principle would point us in the direction of creating a few files that define those container templates and let the children extend them (so we only define the containers once per layout).

I am awful at conveying what I'm asking haha! Once again, sorry!

**Comment by jmm28** [comment]
I think that this layout could work well. Which pages would have which layouts?

**Comment by kiserd** [comment]
I think that is up to developer discretion based on which structure fits most naturally with what is being presented. My interpretation is that the main point is that we provide the developer with a standardized set of structures to choose from (one container, two, etc). I love the idea, viewers will navigate our website and walk away with feelings of consistency... as opposed to every page having an ad-hoc layout/structure.

**Comment by stuart909** [comment]
when a user types in a route, we specify the lowest child, or children.  Those views will extend a parent, and sometimes, those parents extend a parent.  By rendering any given child, or groups of children, they will extend their parents up the hierarchy and the page is rendered.

**Comment by jmm28** [comment]
I started a document that summarizes/outlines the site's layout structure (https://docs.google.com/document/d/1pJ5eJZlbwtkLKUmWHS3TjFe1EF7I-aWD7RMwFW32uYo/edit#). Please feel free to add/edit/refine details as needed!!

**Comment by kiserd** [comment]
I tossed together a quick visualization of how I'm reading this proposal #57. I'll take a peek in the morning to see how off base I am.
