### ISSUE TITLE
remove right password link

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#74]
remove right password link. It's redundant:
![image](https://user-images.githubusercontent.com/58710710/179154674-46826c9b-4176-4369-8d08-4a2e34bcc278.png)

**Comment by stuart909** [comment]
git fetch origin
git checkout 74-remove-right-password-link

**Comment by DanielRiquelmeReb** [comment]
I've created a pull request for this issues
