### ISSUE TITLE
edit profile must function

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#76]
edit profile must function:
![image](https://user-images.githubusercontent.com/58710710/179154789-e9922955-9928-4852-a7e1-c20e46743d93.png)

**Comment by stuart909** [comment]
git fetch origin
git checkout 76-edit-profile-must-function

**Comment by achen236** [comment]
The edit profile function seems to function already. Is there something else to be added?

**Comment by jmm28** [comment]
Like Andy asked, is there something in particular that needs to be changed or added? I'm able to change my name and email.
