### ISSUE TITLE
Company Model

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#78]
Create the company model  in models.py to fulfill the following requirements:

- id
- name
- address1
- address2
- city
- state
- zip
- country
- phone
- email
- members

**Comment by stuart909** [comment]
git fetch origin
git checkout 78-company-model

**Comment by jmm28** [comment]
How is the user's company info accessed in the code (i.e. is it through something like current_user.company_info in routes.py)?

**Comment by stuart909** [comment]
Kartik started and Jega corrected the model.  Thanks a bunch.
