### ISSUE TITLE
company info page

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#79]
create the front-end form for company info for the following criteria:
- id
- name
- address1
- address2
- city
- state
- zip
- country
- phone
- email
- members

NOTE:  We must be able to read and update the info.

**Comment by stuart909** [comment]
git fetch origin
git checkout 79-company-info-page

**Comment by jmm28** [comment]
How is the user's company info accessed in the code (i.e. is it through something like current_user.company_info in routes.py)?

(I originally had this comment in #78, but it's more relevant to this issue.)

**Comment by stuart909** [comment]
> How is the user's company info accessed in the code (i.e. is it through something like current_user.company_info in routes.py)?
> 
> (I originally had this comment in #78, but it's more relevant to this issue.)

There is 1 of 2 scenarios if a User gets a relational mapping to a company membership.

If we borrow from the role membership table and keep the relationship similar, then current_user.company_whatever is a list of company_membership tables.  You would have to handle the iteration of the list and then specify the column you are looking for through a property reference.  IE:

current_user.company_whatever[0].name # assuming name is the membership column you are asking for.  company_whatever is whatever the name of the company table reference in the user model is.
