### ISSUE TITLE
Forum Form

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#86]
**Description**
Please create a web form for rendering the current forum view.  

**Details**
We need to render the tree structure of all the titles of posts that are in the database.  We first start rendering the threads, which are groups or folders containing posts.  Then we render the root title links.  When we click those, we either load a post, or we dive deeper into the folder structure of a group / thread / folder.

**Parent Issue**
#84 

**Additional context**
This excludes an actual post, but rather, we are rendering the forum tree structure to allow the user to filter and select posts.  We will start with basic features first and get more advanced in a later iteration of the project.

**Comment by stuart909** [comment]
git fetch origin
git checkout 86-forum-form

**Comment by achen236** [comment]
If I'm understanding the structure of the forum correctly, I think there needs to be a data model for folders to know what the parent of the folder is, correct? I'm asking this because I want to make sure I understand the structure and create a dummy variable of posts and threads to test render the view.

**Comment by stuart909** [comment]
the thread would be the folder ID.  We shouldn't need a data model for the folder structure at this level in our adventure.  Simply specifying a thread or folder ID works.  The query would look like:

folder = select from forumtable where thread.id=id limit range.  If we evaluate if the thread.id numbers match what we look for then select our range of posts to put into the view.  We do that in the event we limit the page to 10 or 20, or we are looking at 30 of 50, something like that.  We need to be able to return only what the user needs.

**Comment by achen236** [comment]
> the thread would be the folder ID. We shouldn't need a data model for the folder structure at this level in our adventure. Simply specifying a thread or folder ID works. The query would look like:
> 
> folder = select from forumtable where thread.id=id limit range. If we evaluate if the thread.id numbers match what we look for then select our range of posts to put into the view. We do that in the event we limit the page to 10 or 20, or we are looking at 30 of 50, something like that. We need to be able to return only what the user needs.

So if we want to get a folder from the database, how would we differentiate a folder from a post? I'm thinking we could get see if the post has no content then we know it's a folder?

**Comment by stuart909** [comment]
the folderID, or threadID, will tell us what folder we should put in the thing.  Here is a picture:

![image](https://user-images.githubusercontent.com/58710710/181448756-b0edfa60-2cfe-400c-b417-4afffba29b8f.png)

**Comment by stuart909** [comment]
We need to break this down into parts.

- Forum_main should be a simple jinja template that breaks down the main forum view that isn't necessarily populated with folder views or post views
- We need post views that render what the post looks like and loads in dynamic data into the post
- We need new post view that will dynamically load into forum_main and replace posts because we are writing a new post
- The same goes for comment views etc
