### ISSUE TITLE
Data Model: Forum Post

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#90]
**Description**
Please create the ORM data model for the forum post

**Details**

- id
- title
- content
- thread
- author
- tags
- date

**Parent Issue**
#84

**Child Issues**
#97

**Comment by stuart909** [comment]
git fetch origin
git checkout 90-data-model-forum-post

**Comment by loknara** [comment]
Would we want to add a delete feature for both the Post(#90) and for the Comment(#91)?

**Comment by stuart909** [comment]
yes

**Comment by stuart909** [comment]
added child issue #97
