### ISSUE TITLE
Data Model: Forum Comment

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#91]
**Description**
Please create the ORM data model for the forum post user comment

**Details**

- id
- postid
- content
- author
- date

**Parent Issue**
#84

**Child Issues**
#98

**Comment by stuart909** [comment]
git fetch origin
git checkout 91-data-model-forum-comment

**Comment by stuart909** [comment]
added child issue #98

**Comment by achen236** [comment]
I'm getting errors when trying to run branch 91-data-model-forum-comment. After trying to fixing the models.py by matching the tablenames, ForeignKeys, and relationships, I still end up with a NoForeignKeysError
