### ISSUE TITLE
#91 Delete Feature

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#98]
**Description**
#91 needs a delete function

**Details**
We need a front-end button created that adds a delete option somewhere on the page.  The delete function should only be permitted if the owner of the post is the same as the current_user, OR if the user is admin.  We render the option with this criteria and the function also checks this criteria in order to execute the delete query.

**Parent Issue**
#91

**Comment by stuart909** [comment]
git fetch origin
git checkout '98-91-delete-feature'

**Comment by jmm28** [comment]
Should I create a temporary file containing the button/function to later be copied and pasted into the completed comments section?

**Comment by stuart909** [comment]
yes

**Comment by jmm28** [comment]
As suggested in #119, I rewrote the delete function I had in routes.py (which should eventually be moved to forums.py, as the back-end has created).
